# Dockerfile for FastAPI
FROM python:3.12

# Install FastAPI and libvirt-python
RUN apt update && apt install --no-install-recommends -y python3-libvirt gcc pkg-config libvirt-dev openssh-client

# Add application code
COPY ./docker-backend/app /app
COPY ./docker-backend/scripts /app/scripts

# Define the working directory
WORKDIR /app

RUN pip3 install -r ./requirements.txt

RUN mkdir -p /root/.ssh && \
    touch /root/.ssh/known_hosts && \
    ssh-keygen -t rsa -b 2048 -f /root/.ssh/id_rsa -q -N "" && \
    chmod 700 /root/.ssh && \
    chown -R root:root /root/.ssh

# Expose the port for FastAPI
EXPOSE 8000

# Run the FastAPI server
CMD ["sh","/app/scripts/start.sh"]

